### ISSUE TITLE
Hinweis, dass Maschinen erst am Sonntag zur Verfügung stehen

### ISSUE THREAD

**Issue by AndreasUfert** [andreasscherbaum/ansible-workshop-clt-2018#15]

**Comment by AndreasUfert** [comment]
@andreasscherbaum Das vorher Erstellen und dann wieder herunterfahren wird nicht gehen: Die Instanzen verlieren beim Herunterfahren ihre public IP und kommen beim Start mit anderen wieder hoch. Die könnte man reservieren, wenn man ElasticIPs assoziiert. Aber es gibt ein Limit von 5 ElasticIPs pro Account (ipv4-Mangel).

Ich habe ipv6, möchte mich aber darauf nicht verlassen, weder im WLAN des CLT noch auf den Clients der Teilnehmer.

Also: Hochfahren der Instanzen am Sonntagmorgen, 1-2h vor dem Workshop. Ich werde dann auf Bounces bei den Mails individuell eingehen müssen.

**Comment by andreasscherbaum** [comment]
Wie wäre es mit zwei E-Mails? Eine, ein paar Tage vorher, in der steht was die Leute alles brauchen. Und der Hinweis dass die eigentlichen Zugangsdaten erst am Sonntag kommen.
Die zweite dann am Sonntag morgen.

**Comment by AndreasUfert** [comment]
Ja, das ginge. So würde man bouncende Mails vorher klären können.
Vorab-Mail:
- Willkommen
- git-repo auschecken
- ansible installieren aus Distribution, Versionscheck auf 2.x
- Hinweis darauf, dass weitere Instruktionen und Zugangsdaten unmittelbar vor dem Workshop folgen
- Weiteres?

**Comment by andreasscherbaum** [comment]
* ssh muss installiert und konfiguriert sein
* Datum, Uhrzeit und Raum für den Workshop.
* Kontaktdaten für Rückfragen
