### ISSUE TITLE
Übung 01-ssh

### ISSUE THREAD

**Issue by andreasscherbaum** [andreasscherbaum/ansible-workshop-clt-2018#4]
Mittels ssh auf die Maschine verbinden

**Comment by andreasscherbaum** [comment]
Mir ist nicht ganz klar ob wir nur "ssh" testen wollen, oder mittels Ansible und "ssh" auf der Maschine einloggen wollen. Das testen wir ja dann auch in 02-ping ...

**Comment by AndreasUfert** [comment]
Wenn ssh-Test (um zu verstehen, dass das eine Voraussetzung ist), dann mit -i <keyfile> und ubuntu@<ip>.

Ich denke aber, das kann entfallen. Ping ist OK
